

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Liss Gaibor
 */
public class LISTADO extends javax.swing.JFrame {

    /**
     * Creates new form LISTADO
     */
    public static Connection sql;
    public static Statement s;
    DefaultTableModel modelo;
    public LISTADO() {
        initComponents();
        this.setBounds(200, 100, 950, 550);
        listar();
    }
    public void listar(){
        String Titulo[]={"Id","Cedula","Nombre","Apellido","Telefono","Direcciòn","Placa","Modelo","Color"};
        String registro[]=new String[9];
        modelo= new DefaultTableModel(null,Titulo);
        Conexion j=new Conexion(); 
        j.conectar();
        sql=j.sql;
        try {
            s = sql.createStatement();
            ResultSet rs = s.executeQuery("select * from cliente_mes");
            while (rs.next()){
                registro[0]=rs.getString("id_cli");
                registro[1]=rs.getString("cedula");
                registro[2]=rs.getString("nombre");
                registro[3]=rs.getString("apellido");
                registro[4]=rs.getString("telefono");
                registro[5]=rs.getString("direccion");
                registro[6]=rs.getString("placa");
                registro[7]=rs.getString("modelo");
                registro[8]=rs.getString("color");
                modelo.addRow(registro);
            }
            jTable2.setModel(modelo);
        } catch (SQLException ex) {
            
        }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 150, 760, 260);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGOGARAGE2.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 60);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        jLabel1.setText("AUTO COBRADOR \"JS\"");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 340, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton2.setText("EDITAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(810, 200, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("LISTADO DE PROPIETARIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 100, 200, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(810, 250, 100, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FONDO3.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 940, 540);

        jMenuBar1.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jMenu3.setText("INICIO");
        jMenuBar1.add(jMenu3);

        jMenu1.setText("DISPONIBILIDAD");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("REPORTE");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("REGISTRO");
        jMenuBar1.add(jMenu5);

        jMenu7.setText("COBRO");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable2.getSelectedRow();
        String id=jTable2.getValueAt(row, 0).toString();
        System.out.println(id);
        Conexion j=new Conexion();
        j.conectar();
        j.eliminar("DELETE FROM cliente_mes WHERE id_cli='"+id+"'");
        listar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RegistroMes h=new RegistroMes();
        int row = jTable2.getSelectedRow();
        h.cont=1;
        h.id=jTable2.getValueAt(row, 0).toString();
        h.cedula=jTable2.getValueAt(row, 1).toString();
        h.nombre=jTable2.getValueAt(row, 2).toString();
        h.apellido=jTable2.getValueAt(row, 3).toString();
        h.telefono=jTable2.getValueAt(row, 4).toString();
        h.direccion=jTable2.getValueAt(row, 5).toString();
        h.placa=jTable2.getValueAt(row, 6).toString();
        h.modelo=jTable2.getValueAt(row, 7).toString();
        h.color=jTable2.getValueAt(row, 8).toString();
        this.setVisible(false);
        new RegistroMes().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LISTADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LISTADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LISTADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LISTADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LISTADO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
