/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Liss Gaibor
 */
public class RegistroMes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVehiculo
     */
    public static String id;
    public static String cedula;
    public static String nombre;
    public static String apellido;
    public static String telefono;
    public static String direccion;
    public static String placa;
    public static String modelo;
    public static String color;
    public static int cont=0;
    public RegistroMes() {
        initComponents();
        this.setBounds(300, 100, 820, 600);
        if(cont==1){
        textcedula.setText(cedula);
        textnombre.setText(nombre);
        textapellido.setText(apellido);
        texttelefono.setText(telefono);
        textdireccion.setText(direccion);
        textplaca.setText(placa);
        textmodelo.setText(modelo);
        textcolor.setText(color);
        jButton3.setVisible(false);
        jButton1.setVisible(true);
        }else{
        jButton3.setVisible(true);
        jButton1.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textmodelo = new javax.swing.JTextField();
        textplaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textcolor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textnombre = new javax.swing.JTextField();
        textcedula = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        texttelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textdireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textapellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        jLabel1.setText("AUTO COBRADOR \"JS\"");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 340, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VEHÍCULO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 11))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("PLACA:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 40, 50, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("MODELO:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 80, 60, 14);

        textmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textmodeloActionPerformed(evt);
            }
        });
        jPanel2.add(textmodelo);
        textmodelo.setBounds(150, 70, 180, 30);

        textplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textplacaActionPerformed(evt);
            }
        });
        jPanel2.add(textplaca);
        textplaca.setBounds(150, 30, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("COLOR:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 120, 40, 14);
        jPanel2.add(textcolor);
        textcolor.setBounds(150, 110, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 80, 610, 170);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGOGARAGE2.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 60);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROPIETARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 11))); // NOI18N
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("CEDULA:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 40, 50, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("NOMBRE: ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 70, 60, 14);

        textnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnombreActionPerformed(evt);
            }
        });
        jPanel4.add(textnombre);
        textnombre.setBounds(90, 70, 180, 30);

        textcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcedulaActionPerformed(evt);
            }
        });
        jPanel4.add(textcedula);
        textcedula.setBounds(90, 30, 110, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("TELEFONO:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(20, 150, 60, 14);
        jPanel4.add(texttelefono);
        texttelefono.setBounds(90, 150, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("DIRECCIÓN:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 200, 70, 14);
        jPanel4.add(textdireccion);
        textdireccion.setBounds(90, 190, 250, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("APELLIDO: ");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 110, 60, 14);
        jPanel4.add(textapellido);
        textapellido.setBounds(90, 110, 130, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 270, 610, 230);

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 290, 110, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton2.setText("VER LISTADO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 230, 110, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton3.setText("AGREGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 160, 110, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FONDO3.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 810, 540);

        jMenuBar1.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jMenu3.setText("INICIO");
        jMenuBar1.add(jMenu3);

        jMenu1.setText("DISPONIBILIDAD");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("REPORTE");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("REGISTRO");
        jMenuBar1.add(jMenu5);

        jMenu7.setText("COBRO");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textplacaActionPerformed

    private void textnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnombreActionPerformed

    private void textcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcedulaActionPerformed

    private void textmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textmodeloActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        Conexion j=new Conexion();
        j.conectar();
        j.insertar("INSERT INTO cliente_mes(cedula,nombre,apellido,telefono,direccion,placa,modelo,color) VALUES('"+textcedula.getText()+"','"+textnombre.getText()+"','"+textapellido.getText()+"','"+texttelefono.getText()+"','"+textdireccion.getText()+"','"+textplaca.getText()+"','"+textmodelo.getText()+"','"+textcolor.getText()+"')"); 
            System.out.println("EXITO");
        } catch (Exception e) {
            System.out.println("ERROR");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new LISTADO().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cont=0;
        try {
        Conexion j=new Conexion();
        j.conectar();
        j.editar("UPDATE cliente_mes SET cedula='"+textcedula.getText()+"',nombre='"+textnombre.getText()+"',apellido='"+textapellido.getText()+"',telefono='"+texttelefono.getText()+"',direccion='"+textdireccion.getText()+"',placa='"+textplaca.getText()+"',modelo='"+textmodelo.getText()+"',color='"+textcolor.getText()+"' WHERE id_cli='"+id+"'"); 
            System.out.println("EXITO");
        } catch (Exception e) {
            System.out.println("ERROR");
        }
        this.setVisible(false);
        new LISTADO().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField textapellido;
    private javax.swing.JTextField textcedula;
    private javax.swing.JTextField textcolor;
    private javax.swing.JTextField textdireccion;
    private javax.swing.JTextField textmodelo;
    private javax.swing.JTextField textnombre;
    private javax.swing.JTextField textplaca;
    private javax.swing.JTextField texttelefono;
    // End of variables declaration//GEN-END:variables
}
